CREATE TABLE IF NOT EXISTS person (
	id SERIAL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	surname VARCHAR(32) NOT NULL,
	email VARCHAR(48) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS telephone (
	id SERIAL PRIMARY KEY AUTO_INCREMENT,
	number VARCHAR(15) UNIQUE NOT NULL,
	person_id INTEGER NOT NULL REFERENCES preson(id)
	--FOREIGN KEY (id_person) REFERENCES person(id)
);