CREATE TABLE IF NOT EXISTS public.person (
	id SERIAL NOT NULL,
	name VARCHAR(32) NOT NULL,
	surname VARCHAR(32) NOT NULL,
	email VARCHAR(48) UNIQUE NOT NULL,
	CONSTRAINT person_pk PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS public.telephone (
	id SERIAL NOT NULL,
	number VARCHAR(16) UNIQUE NOT NULL,
	person_id INTEGER NOT NULL,
	FOREIGN KEY (person_id) REFERENCES person(id),
	CONSTRAINT telefone_pk PRIMARY KEY(id)
);